// `useHello` is generated by orval from the backend module's OpenAPI schema
// (run `pnpm run build:modules`, which regenerates `src/api/example.ts`).
import { useHello } from "../api/example";

export default function Hello() {
  const { data, isPending, isError } = useHello();

  return (
    <div>
      <h1>Example module</h1>
      <p>
        {isPending
          ? "Loading…"
          : isError
            ? "Could not reach the backend module."
            : data?.message}
      </p>
      <p>
        Edit <code>frontend-modules/example</code> (frontend) and{" "}
        <code>backend-modules/example</code> (backend) to build your own module.
      </p>
    </div>
  );
}
